version: '3.8'

services:
  itv:
    build: .
    restart: unless-stopped
    ports:
      - "1995:8000"
    volumes:
      - /home/dietpi/itv/stack.env:/app/stack.env:ro
      - /home/dietpi/itv/logs:/app/logs
